name: "[Workflow] PR"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  branch_name:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main
#  branch_name:
#    runs-on: ubuntu-latest
#    name: Extract branch name
#    outputs:
#      raw_branch: ${{ steps.extract_branch.outputs.branch }}
#      sanitised_branch: ${{ steps.extract_branch.outputs.branchsane }}
#    steps:
#      - name: Extract branch
#        shell: bash
#        run: |
#          echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
#          echo "##[set-output name=branchsane;]$(echo ${GITHUB_HEAD_REF} | tr -cd '[:alnum:]')"
#        id: extract_branch

  create_tags:
    name: Create Tags
    needs: ['branch_name']
    uses: ./.github/workflows/tags_job.yml
    with:
#      branch_name: ${{ needs.branch_name.outputs.raw_branch }}
      branch_name: ${{ needs.branch_name.outputs.raw_branch_name }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}