name: "[Workflow] PR"

on:
  push:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  branch_name:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main
#  branch_name:
#    runs-on: ubuntu-latest
#    name: Extract branch name
#    outputs:
#      raw_branch: ${{ steps.extract_branch.outputs.branch }}
#      sanitised_branch: ${{ steps.extract_branch.outputs.branchsane }}
#    steps:
#      - name: Extract branch
#        shell: bash
#        run: |
#          echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
#          echo "##[set-output name=branchsane;]$(echo ${GITHUB_HEAD_REF} | tr -cd '[:alnum:]')"
#        id: extract_branch

  create_tags:
    name: Create Tags
    needs: ['branch_name']
    uses: ./.github/workflows/tags_job.yml
    with:
#      branch_name: ${{ needs.branch_name.outputs.raw_branch }}
      branch_name: ${{ needs.branch_name.outputs.raw_branch_name }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  create_release:
    name: Create Release
    needs: ['create_tags']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.create_tags.outputs.version_tag }}
          release_name: Release ${{ needs.create_tags.outputs.version_tag }}
          body: |
            Changes in this Release
            - Jim change
            - Second Change
          draft: false
          prerelease: false

