name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  checks: read
  contents: write
  deployments: none
  issues: none
  packages: none
  pull-requests: write
  repository-projects: none
  security-events: write
  statuses: none

jobs:
  branch_name:
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main

  create_tags:
    name: Create Tags
    needs: ['branch_name']
    uses: ./.github/workflows/tags_job.yml
    with:
      branch_name: ${{ needs.branch_name.outputs.raw_branch_name }}
    secrets:
      source_github_token: ${{ secrets.GITHUB_TOKEN }}

  docker_build_scan_push:
    name: Build, Scan and Push.
    needs: ['create_tags']
    uses: ./.github/workflows/docker_build.yml
    with:
      ecr_repository: '311462405659.dkr.ecr.eu-west-1.amazonaws.com'
      lambda_names: '["deputy-reporting-lambda", "deputy-reporting-mock-sirius"]'
      tag: ${{ needs.create_tags.outputs.version_tag }}
    secrets:
      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}

  test_a_thing:
    name: Check images
    needs: ['docker_build_scan_push']
    runs-on: ubuntu-latest
    steps:
      - name: View images
        id: images
        run: docker image ls

#  docker_scan:
#    name: Scans the images
#    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-containers-trivy-to-github-security.yml@main
#    with:
#      tagged_images: [
#          "${{ inputs.ecr_repository }}/integrations/deputy-reporting-lambda:${{ inputs.tag }}",
#          "${{ inputs.ecr_repository }}/integrations/deputy-reporting-mock-sirius:${{ inputs.tag }}"
#      ]

#  tfsec:
#    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-pr-feedback.yml@main
#    with:
#      terraform_path: '["terraform/account", "terraform/environment"]'
#      soft_fail: true
#    secrets:
#      source_github_token: ${{ secrets.GITHUB_TOKEN }}
#
#  terraform_account_workflow:
#    name: Terraform Account
#    needs: ['tfsec', 'docker_build_scan_push']
#    uses: ./.github/workflows/terraform_plan_job.yml
#    with:
#      terraform_path: 'terraform/account'
#      workspace: development
#    secrets:
#      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
#      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
#
#  terraform_environment_workflow:
#    name: Terraform Environment
#    needs: ['terraform_account_workflow']
#    uses: ./.github/workflows/terraform_plan_job.yml
#    with:
#      terraform_path: 'terraform/environment'
#      workspace: development
#    secrets:
#      aws_access_key_id_actions: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
#      aws_secret_access_key_actions: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
